config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  root to: 'home#index'

  resources :categories, :paintings, only: [:index, :new, :create, :delete]
  resources :categorizations, only: [:create,:delete]
  
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
end

app/models/cateogry.rb
class Cateogry < ActiveRecord::Base
end

app/models/painting.rb
class Painting < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/categorizations_controller.rb
class CategorizationsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

	def new
		@painting = Painting.new
	end

	def create
		@painting = Painting.new(painting_params)
		if @painting.save
			redirect '/'
		else
			render 'new'
		end
	end


	private 

	def painting_params
		params.require(:painting).permit(:name,:description,:url)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorizations_helper.rb
module CategorizationsHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/home/index.html.haml
%h1 Welcome

%br 

- if administrator_signed_in?
	= link_to "Add new paintings", new_painting_path
	= link_to "Add new categories", new_category_path
- else 
	= link_to "Sign In", new_administrator_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>